pipeline {
    agent {
        label "master"
    }

    options {
        // skipDefaultCheckout()
        timeout(time: 5, unit: 'MINUTES')
        timestamps()
    }

    stages {
        stage('test') {
            steps {
                echo "hello world!"
            }
        }

        stage('Preparation') {
            steps {
                echo "********************* Stage: Preparation *********************"
                echo "--------------------- Stpe: Reading Environment ---------------------"
                echo "Environment: ${params.Environment}"
                echo "--------------------- Stpe: Reading Branch ---------------------"
                echo "Branch/Tag: ${params.Branch}"
            }
        }
    }
}